import { EXIT_STRATEGY_BROWSER_SOURCE } from "./exit-strategy";

export function buildPage(exitStrategyEnabled = true) {
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>零度雷达 ZeroSlope · 4H EMA99 策略适配器</title>
<style>
:root{color-scheme:dark;--bg:#07100e;--card:#0d1916;--line:#20332d;--text:#e9f5f0;--muted:#8aa399;--green:#35d59a;--red:#ff6b6b}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% 0,#143027 0,#07100e 42%);color:var(--text);font:14px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}
main{max-width:1440px;margin:auto;padding:32px 20px 60px}header{display:flex;gap:20px;align-items:end;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:24px}.basis{margin:10px 0 0;color:#a8beb5;font-size:12px}
h1{font:700 clamp(25px,4vw,44px)/1.1 system-ui;margin:0}h2{font:700 19px system-ui;margin:0 0 16px}.eyebrow,.muted{color:var(--muted)}
button{border:0;border-radius:8px;background:var(--green);color:#03120d;font:700 15px system-ui;padding:13px 22px;cursor:pointer;min-height:46px}button:disabled{opacity:.55;cursor:wait}.mini{min-height:30px;padding:5px 9px;font-size:12px}.short{background:var(--red)}.ghost{background:#23352f;color:var(--text)}
.background-tag{display:block;width:max-content;max-width:100%;margin-top:7px;color:var(--muted);font:500 11px/1.35 system-ui;letter-spacing:.02em;white-space:nowrap}.background-tag.up{color:#68b99a}.background-tag.down{color:#ce8585}
#status{margin:18px 0;min-height:24px}.error{color:#ff9b9b;white-space:pre-wrap}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}
.card{background:color-mix(in srgb,var(--card) 90%,transparent);border:1px solid var(--line);border-radius:12px;padding:17px}.value{font:700 25px system-ui}.up,.market-up{color:var(--green)}.down,.market-down{color:var(--red)}.pinned{margin:20px 0 0;grid-template-columns:repeat(5,minmax(0,1fr))}.pinned .card{min-height:154px;border-color:#315247}.pinned-symbol{font:700 18px system-ui;margin:5px 0}.pinned-price{font:800 25px system-ui;margin-top:8px}.pinned-change{font:700 16px system-ui;margin:2px 0 8px}.pinned-angle{font-size:12px;color:var(--muted)}
.section{margin-top:30px}.section-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px}.section-title h2{margin:0}.section-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.strategy{border-color:#2b6651;background:linear-gradient(135deg,#10251e,#0d1916)}.strategy h2{font-size:22px}.strategy-note{margin:-8px 0 18px}.strategy-detail{display:block;margin-top:5px;color:var(--muted);font-size:12px}.signal-box{display:inline-flex;align-items:center;flex-wrap:wrap;gap:5px 12px;width:fit-content;margin-top:10px;padding:8px 11px;border:1px solid #30433c;border-radius:9px;background:#091410;color:var(--muted)}.signal-box b{font:750 15px system-ui;color:var(--text)}.signal-box.up{border-color:#275c49;background:#0b1d17}.signal-box.up b{color:#58d8a7}.signal-box.down{border-color:#683939;background:#1c1111}.signal-box.down b{color:#ff7b7b}.signal-box .far{color:#ffc36b;font-weight:700}.groups{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.group ul{margin:0;padding:0;list-style:none}.group li{display:grid;grid-template-columns:80px 1fr auto;gap:10px;padding:10px 0;border-top:1px solid var(--line)}#strategy-list li{grid-template-columns:150px minmax(0,1fr) auto;align-items:start;gap:18px;padding:16px 0}#strategy-list li>b{display:flex;flex-direction:column;align-items:flex-start;gap:2px;font:750 15px/1.35 system-ui;letter-spacing:.01em}#strategy-list li>span:nth-child(2){min-width:0;padding-top:1px}#strategy-list li>span:last-child{padding-top:1px}.position-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.score{font:800 38px system-ui}.live-price{display:inline-flex;align-items:center;gap:7px;margin:2px 0 10px;padding:5px 9px;border:1px solid #315247;border-radius:999px;background:#10251e}.live-dot{width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 8px var(--green)}.position-actions{display:flex;gap:8px;margin-top:12px}.rule-list{margin:10px 0 0;padding-left:20px}.rule-list li{margin:4px 0}dialog{width:min(520px,calc(100% - 24px));border:1px solid var(--line);border-radius:12px;background:var(--card);color:var(--text);padding:22px}dialog::backdrop{background:#000a}label{display:block;margin:12px 0 5px;color:var(--muted)}input,select{width:100%;padding:11px;border:1px solid var(--line);border-radius:7px;background:#07100e;color:var(--text);font:inherit}.dialog-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:20px}
.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:12px}table{width:100%;border-collapse:collapse;white-space:nowrap;background:var(--card)}th,td{padding:10px 11px;text-align:right;border-bottom:1px solid var(--line)}
th{position:sticky;top:0;background:#13231e;color:var(--muted);font-size:12px;cursor:pointer}th:nth-child(2),td:nth-child(2){text-align:left;position:sticky;left:0;background:inherit}footer{margin-top:32px;color:var(--muted);text-align:center}
@media(max-width:1100px) and (min-width:761px){.pinned{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:760px){main{padding:20px 12px 40px}header{align-items:stretch;flex-direction:column}.grid,.groups,.position-grid{grid-template-columns:1fr}.section-title{align-items:flex-start;flex-direction:column}.section-actions{width:100%;justify-content:flex-start}.group li{grid-template-columns:72px 1fr auto}#strategy-list li{grid-template-columns:minmax(0,1fr) auto;gap:10px 12px;padding:15px 0}#strategy-list li>span:nth-child(2){grid-column:1/-1;grid-row:2}#strategy-list li>span:last-child{grid-column:2;grid-row:1}.signal-box{width:100%}header button{width:100%}}
</style></head><body><main>
<header><div><div class="eyebrow">ZEROSLOPE · 4H EMA99 STRATEGY SCANNER</div><h1>零度雷达</h1><p class="muted">4H EMA99 策略适配器 · 扫描高流动性资产，优先寻找角度最接近 0° 的标的。</p><p class="basis">计价基准：USDT · 行情默认使用 USDⓈ-M Mark Price</p></div><button id="scan">立即扫描</button></header>
<section id="positions" class="section"><div class="section-title"><div><h2>已持有仓位</h2>${exitStrategyEnabled ? '<div class="muted">持仓退出策略 1.0 · ATR 波动保护与分批平仓</div>' : ""}</div><div class="section-actions"><button id="share-positions" class="mini ghost">分享持仓</button><button id="manual-position" class="mini ghost">＋ 手动新增</button></div></div><div id="sync-notice" class="muted" hidden></div><div id="position-list" class="position-grid"></div></section>
<div id="status" class="muted">点击按钮实时请求官方行情。</div>
<section id="pinned" class="grid pinned" hidden></section>
<section id="market" class="grid" hidden></section>
<section id="strategy" class="section" hidden><h2>候选模块</h2><div class="card strategy"><h2>EMA99 零度筛选器 1.1</h2><p class="muted strategy-note">前段有效曲线下跌后穿上 0° 看多，前段有效曲线上涨后穿下 0° 看空；短暂反向波动不登记为新趋势。用 99 根 4H 均线寻找右侧反转候选。</p><div class="group" id="strategy-list"></div></div></section>
<section id="highlights" class="section" hidden><h2>趋势观察分组</h2><div class="groups" id="groups"></div></section>
<section id="full" class="section" hidden><h2>完整扫描表 <span class="muted">（点击表头排序）</span></h2><div class="table-wrap"><table><thead id="head"></thead><tbody id="body"></tbody></table></div></section>
<section id="issues" class="section" hidden><h2>跳过的标的</h2><div class="card error" id="issue-list"></div></section>
<dialog id="position-dialog"><form id="position-form"><h2>添加已持有仓位</h2><label for="pos-symbol">资产</label><input id="pos-symbol" required autocomplete="off" placeholder="例如 BTC、NVDA 或 XAU"><div id="symbol-help" class="muted">输入资产简称即可；内部会自动匹配可用的 USDT 或 USDC 行情。</div><label for="pos-side">方向</label><select id="pos-side"><option value="long">多单</option><option value="short">空单</option></select><label for="pos-entry">开仓价（建议填写）</label><input id="pos-entry" type="number" min="0" step="any" placeholder="用于计算当前浮盈亏"><label for="pos-stop">结构止损价（建议填写）</label><input id="pos-stop" type="number" min="0" step="any" placeholder="触及后直接进入离场检查"><div class="dialog-actions"><button type="button" class="ghost" id="pos-cancel">取消</button><button type="submit">保存仓位</button></div></form></dialog>
<footer>技术指标不构成投资建议。</footer></main>
<script>
const EXIT_STRATEGY_ENABLED=${JSON.stringify(exitStrategyEnabled)};
${EXIT_STRATEGY_BROWSER_SOURCE}
const $=s=>document.querySelector(s),fmt=(n,d=2)=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:d}),pct=n=>(n>=0?'+':'')+n.toFixed(2)+'%',ang=n=>(n>=0?'+':'')+n.toFixed(3)+'°',time=t=>new Date(t).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
const cols=[['rank','成交额排名'],['symbol','资产'],['quoteVolume','24h Quote Volume'],['openInterest','Open Interest 数量'],['openInterestNotional','OI 名义价值'],['markPrice','Mark Price'],['ema99','EMA99'],['distancePct','距 EMA99'],['angle5','5根角度'],['angle10','10根角度'],['angle20','20根角度'],['emaChange10Pct','EMA 10根累计变化'],['trend','趋势分类'],['momentum','角度动量'],['lastClosedTime','已收盘4H结束时间']];
let data,sortKey='angle10Abs',sortAsc=true;
function klass(n){return n>0?'up':n<0?'down':''}
function val(r,k){if(k==='symbol')return baseKey(r[k]);if(['distancePct','emaChange10Pct'].includes(k))return pct(r[k]);if(k.startsWith('angle'))return ang(r[k]);if(k==='lastClosedTime')return time(r[k]);if(['quoteVolume','openInterest','openInterestNotional'].includes(k))return fmt(r[k],0);if(['markPrice','ema99'].includes(k))return fmt(r[k],8);return r[k]}
function table(){const rows=[...data.rows].sort((a,b)=>{const x=sortKey==='angle10Abs'?Math.abs(a.angle10):a[sortKey],y=sortKey==='angle10Abs'?Math.abs(b.angle10):b[sortKey];return (typeof x==='number'?x-y:String(x).localeCompare(String(y)))*(sortAsc?1:-1)});$('#head').innerHTML='<tr>'+cols.map(c=>'<th data-k="'+c[0]+'">'+c[1]+((sortKey===c[0]||sortKey==='angle10Abs'&&c[0]==='angle10')?(sortAsc?' ↑':' ↓'):'')+'</th>').join('')+'</tr>';$('#body').innerHTML=rows.map(r=>'<tr>'+cols.map(c=>'<td class="'+(c[0].startsWith('angle')||c[0].endsWith('Pct')?klass(r[c[0]]):'')+'">'+val(r,c[0])+'</td>').join('')+'</tr>').join('');document.querySelectorAll('th').forEach(x=>x.onclick=()=>{const k=x.dataset.k;if(k==='angle10'&&sortKey!=='angle10')sortKey='angle10';else{sortAsc=sortKey===k?!sortAsc:false;sortKey=k}table()})}
function group(title,rows){return '<div class="card group"><h2>'+title+' <span class="muted">'+rows.length+'</span></h2><ul>'+(rows.length?rows.map(r=>'<li><b>'+baseKey(r.symbol)+'</b><span class="'+klass(r.angle10)+'">'+ang(r.angle10)+' · '+r.trend+' · '+r.momentum+'</span><span>'+pct(r.distancePct)+'</span></li>').join(''):'<li class="muted">暂无</li>')+'</ul></div>'}
const POSITION_STORAGE_KEY='zeroslope_positions',POSITION_CONFIG_VERSION=2;
function loadPositions(){try{const value=JSON.parse(localStorage.getItem(POSITION_STORAGE_KEY)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return{}}}
let positions=loadPositions();
function cleanSymbol(value){return value.toUpperCase().replace(/[^A-Z0-9]/g,'')}
function savePositions(){localStorage.setItem(POSITION_STORAGE_KEY,JSON.stringify(positions))}
function parsePositionConfig(text){const config=JSON.parse(text);if(!config||config.app!=='ZeroSlope'||![1,2].includes(config.version)||!config.positions||typeof config.positions!=='object'||Array.isArray(config.positions))throw new Error('不是受支持的 ZeroSlope 持仓配置');const valid={};for(const [rawSymbol,p] of Object.entries(config.positions)){const symbol=cleanSymbol(rawSymbol),entry=Number(p&&p.entry),stop=Number(p&&p.stop);if(!symbol||symbol!==rawSymbol||!p||!['long','short'].includes(p.side)||!Number.isFinite(entry)||entry<0||!Number.isFinite(stop)||stop<0)throw new Error('仓位 '+rawSymbol+' 的字段无效');const t=p.tracking||{},tracking={trackedAt:Number(t.trackedAt)||Date.now(),updatedAt:Number(t.updatedAt)||Date.now(),lastScanAt:Number(t.lastScanAt)||0,bestPrice:Number(t.bestPrice)||0,protectiveStop:Number(t.protectiveStop)||stop};valid[symbol]={side:p.side,entry,stop,tracking}}return valid}
function positionConfig(){return{app:'ZeroSlope',version:POSITION_CONFIG_VERSION,exportedAt:new Date().toISOString(),positions}}
function encodeConfig(config){const bytes=new TextEncoder().encode(JSON.stringify(config)),parts=[];for(let i=0;i<bytes.length;i+=8192)parts.push(String.fromCharCode(...bytes.subarray(i,i+8192)));return btoa(parts.join('')).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'')}
function decodeConfig(value){const base64=value.replace(/-/g,'+').replace(/_/g,'/'),binary=atob(base64+'='.repeat((4-base64.length%4)%4)),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
async function sharePositions(){const url=new URL(location.href);url.hash='positions='+encodeConfig(positionConfig());if(url.href.length>8000){alert('持仓数量过多，暂时无法生成分享链接。');return}if(navigator.share){try{await navigator.share({title:'ZeroSlope 持仓',text:'打开链接即可导入持仓数据',url:url.href});return}catch(e){if(e.name==='AbortError')return}}try{await navigator.clipboard.writeText(url.href);alert('持仓分享链接已复制。另一台设备打开后会自动导入。')}catch{prompt('复制下面的持仓分享链接：',url.href)}}
function importSharedPositions(){if(!location.hash.startsWith('#positions='))return null;const payload=location.hash.slice(11);history.replaceState(null,'',location.pathname+location.search);try{positions=parsePositionConfig(decodeConfig(payload));savePositions();return Object.keys(positions).length}catch(e){return{error:e.message}}}
function openPosition(symbol){const p=positions[symbol]||{};$('#pos-symbol').value=symbol;$('#pos-symbol').readOnly=true;$('#symbol-help').hidden=true;$('#pos-side').value=p.side||'long';$('#pos-entry').value=p.entry||'';$('#pos-stop').value=p.stop||'';$('#position-dialog').showModal()}
function openManualPosition(){$('#pos-symbol').value='';$('#pos-symbol').readOnly=false;$('#symbol-help').hidden=false;$('#pos-side').value='long';$('#pos-entry').value='';$('#pos-stop').value='';$('#position-dialog').showModal();$('#pos-symbol').focus()}
function closePosition(symbol){if(!confirm('确认 '+baseKey(symbol)+' 已经平仓？'))return;delete positions[symbol];savePositions();renderPositions()}
function renderPositions(){const box=$('#position-list'),entries=Object.entries(positions);if(!entries.length){box.innerHTML='<div class="card muted">暂无持仓。可从策略列表选择“持仓”，或手动新增币对。</div>';return}let changed=false;box.innerHTML=entries.map(([symbol,p])=>{const row=data&&(data.positionRows||data.rows).find(r=>r.positionKey===symbol||r.symbol===symbol);if(!row)return'<div class="card"><h2>'+baseKey(symbol)+' · '+(p.side==='long'?'多单':'空单')+'</h2><div class="muted">'+(data?'未找到对应的 USDT/USDC 永续合约。':'等待自动扫描获取实时行情。')+'</div><div class="position-actions"><button class="mini ghost" onclick="openPosition(\\''+symbol+'\\')">编辑</button><button class="mini short" onclick="closePosition(\\''+symbol+'\\')">已平仓</button></div></div>';if(!EXIT_STRATEGY_ENABLED)return'<div class="card"><div class="muted">'+(p.side==='long'?'多单':'空单')+' · '+baseKey(row.symbol)+'</div><div class="live-price"><span class="live-dot"></span><span>现价</span><b>'+fmt(row.markPrice,8)+'</b></div><h2>退出策略未部署</h2><div class="position-actions"><button class="mini ghost" onclick="openPosition(\\''+symbol+'\\')">编辑</button><button class="mini short" onclick="closePosition(\\''+symbol+'\\')">已平仓</button></div></div>';const a=evaluateExitStrategy(p,row);if(JSON.stringify(p.tracking)!==JSON.stringify(a.tracking)){p.tracking=a.tracking;changed=true}const tone=a.closePercentage>=50?'down':a.closePercentage===0?'up':'';return'<div class="card"><div class="muted">'+(p.side==='long'?'多单':'空单')+' · '+baseKey(row.symbol)+(p.entry?' · 开仓 '+fmt(p.entry,8):'')+'</div><span class="background-tag '+(row.dailyBackground?klass(row.dailyBackground.angle10):'')+'">日线 · '+(row.dailyBackground?row.dailyBackground.label:'背景暂不可用')+'</span><div class="live-price"><span class="live-dot"></span><span>现价</span><b>'+fmt(row.markPrice,8)+'</b></div><div class="score '+tone+'">'+a.closePercentage+'<small>%</small></div><h2 class="'+tone+'">'+a.action+'</h2>'+(a.pnl===null?'':'<div>当前浮盈亏：<b class="'+klass(a.pnl)+'">'+pct(a.pnl)+'</b>'+(a.profitR===null?'':' · '+a.profitR.toFixed(2)+'R')+'</div>')+'<div>4H ATR14：<b>'+a.atrPct.toFixed(2)+'%</b> · 近期/基准波动：<b>'+a.volatilityRatio.toFixed(2)+'×</b></div>'+(row.hourly?'<div>1H EMA99：Angle5 <b class="'+klass(row.hourly.angle5)+'">'+ang(row.hourly.angle5)+'</b> · Angle10 <b class="'+klass(row.hourly.angle10)+'">'+ang(row.hourly.angle10)+'</b></div>':'<div class="muted">1H EMA99 暂不可用，不影响 4H 主判断</div>')+(a.protectiveStop>0?'<div>当前保护价：<b>'+fmt(a.protectiveStop,8)+'</b></div>':'')+'<div class="muted">网页追踪始于 '+time(a.tracking.trackedAt)+' · 4H 行情截至 '+time(a.tracking.lastScanAt)+'</div><ul class="rule-list">'+a.reasons.map(x=>'<li>'+x+'</li>').join('')+'</ul><div class="position-actions"><button class="mini ghost" onclick="openPosition(\\''+symbol+'\\')">编辑</button><button class="mini short" onclick="closePosition(\\''+symbol+'\\')">已平仓</button></div></div>'}).join('');if(changed)savePositions()}
function render(d){
data=d;
const m=d.market;
$('#status').textContent='扫描时间（UTC+8）：'+time(d.scannedAt)+' · 最近已收盘4H：'+time(d.lastClosedTime)+' · 耗时 '+fmt(d.durationMs,0)+' ms · 币圈 '+d.composition.crypto+' / 股票 '+d.composition.stocks+' · 成交额 '+d.liquiditySource;
$('#pinned').innerHTML=d.pinned.map(x=>{
  if(!x.row)return'<div class="card"><div class="muted">'+x.label+'</div><div class="pinned-symbol">'+baseKey(x.symbol)+'</div><div class="down">当前不在 USDⓈ-M 永续交易池或数据不可用</div></div>';
  const change=x.row.priceChangePct,changeClass=change>0?'market-up':change<0?'market-down':'';
  return'<div class="card"><div class="muted">'+x.label+'</div><div class="pinned-symbol">'+baseKey(x.symbol)+'</div><div class="pinned-price">'+fmt(x.row.markPrice,8)+'</div><div class="pinned-change '+changeClass+'">24h '+(change>=0?'+':'')+change.toFixed(2)+'%</div><div class="pinned-angle">EMA99角度 '+ang(x.row.angle10)+' · 距EMA '+pct(x.row.distancePct)+'</div></div>'
}).join('');
$('#market').innerHTML=[['市场状态',m.regime,''],['EMA99 向上',m.up.count+' / '+m.up.pct.toFixed(0)+'%','up'],['EMA99 向下',m.down.count+' / '+m.down.pct.toFixed(0)+'%','down'],['基本走平',m.flat.count+' / '+m.flat.pct.toFixed(0)+'%',''],['Price > EMA99',m.above.count+' / '+m.above.pct.toFixed(0)+'%','up'],['Price < EMA99',m.below.count+' / '+m.below.pct.toFixed(0)+'%','down'],['加速上涨',m.acceleratingUp,'up'],['加速下降',m.acceleratingDown,'down']].map(x=>'<div class="card"><div class="muted">'+x[0]+'</div><div class="value '+x[2]+'">'+x[1]+'</div></div>').join('');
const adapted=[...d.rows].sort((a,b)=>Math.abs(a.angle10)-Math.abs(b.angle10));
$('#strategy-list').innerHTML='<ul>'+adapted.map((r,i)=>{
  const tone=r.recommendedSide==='做多'?'up':r.recommendedSide==='做空'?'down':'';
  const signal=r.recommendedSide==='观望'?'<span class="signal-box"><b>观望</b><span>'+(r.curve.confirmed?'等待 EMA99 反向穿越 0°':'前段曲线未确认')+'</span></span>':'<span class="signal-box '+tone+'"><b>推荐'+r.recommendedSide+'</b><span>止损 '+fmt(r.suggestedStop,8)+'</span><span>距现价 '+r.stopDistancePct.toFixed(2)+'%</span>'+(r.stopDistancePct>5?'<span class="far">止损偏远</span>':'')+'</span>';
  return'<li><b>#'+(i+1)+' '+baseKey(r.symbol)+'<small class="background-tag '+(r.dailyBackground?klass(r.dailyBackground.angle10):'')+'">日线 · '+(r.dailyBackground?r.dailyBackground.label:'背景暂不可用')+'</small></b><span><span class="'+klass(r.angle10)+'">'+ang(r.angle10)+' · '+r.trend+' · '+r.momentum+'</span><small class="strategy-detail">前段 '+ang(r.curve.averageAngle)+' · 一致率 '+(r.curve.directionalRatio*100).toFixed(0)+'% · 位移 '+r.curve.netChangePct.toFixed(3)+'%</small>'+signal+'</span><span><button class="mini ghost" onclick="openPosition(&quot;'+r.symbol+'&quot;)">持仓</button></span></li>'
}).join('')+'</ul>';
const h=d.highlights;
$('#groups').innerHTML=group('角度最陡上涨 Top 5',h.steepestUp)+group('角度最陡下跌 Top 5',h.steepestDown)+group('加速上涨',h.acceleratingUp)+group('加速下降',h.acceleratingDown)+group('可能由负转正',h.turningPositive)+group('可能由正转负',h.turningNegative)+group('距离 EMA99 超过 ±5%',h.farFromEma);
['pinned','market','strategy','highlights','full'].forEach(x=>$('#'+x).hidden=false);
sortKey='angle10Abs';sortAsc=true;table();renderPositions();
if(d.errors.length){$('#issues').hidden=false;$('#issue-list').textContent=d.errors.map(e=>baseKey(e.symbol)+': '+e.error).join('\\n')}else $('#issues').hidden=true
}
const API_BASES=['https://fapi.binance.com','https://fapi1.binance.com','https://fapi2.binance.com','https://fapi3.binance.com','https://fapi4.binance.com'];
const SPOT_API_BASES=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com','https://api3.binance.com','https://api4.binance.com'];
// 固定关注配置：后续只需修改这里的 label 和 symbol。
const PINNED_PAIRS=[{label:'比特币',symbol:'BTCUSDT'},{label:'纳指 QQQ',symbol:'QQQUSDT'},{label:'黄金',symbol:'XAUUSDT'},{label:'原油',symbol:'CLUSDT'},{label:'韩指 EWY',symbol:'EWYUSDT'}];
// Binance 官方股票/ETF TradFi 永续候选池；每次按 24h Quote Volume 自动选前 10。
const TRADFI_PAIRS=['XAUUSDT','CLUSDT','QQQUSDT','SPYUSDT','EWYUSDT','EWJUSDT','MSTRUSDT','COINUSDT','HOODUSDT','CRCLUSDT','PAYPUSDT','TSLAUSDT','AMZNUSDT','METAUSDT','GOOGLUSDT','AAPLUSDT','MSFTUSDT','NVDAUSDT','MUUSDT','SNDKUSDT','TSMUSDT','AVGOUSDT','INTCUSDT','PLTRUSDT','BABAUSDT','SKHYNIXUSDT','SAMSUNGUSDT','HYUNDAIUSDT','SKHYUSDT'];
const UNDERLYING_ALIASES={AVGOB:'AVGO',BABAB:'BABA',COINB:'COIN',CRCLB:'CRCL',GOOGLB:'GOOGL',HOODB:'HOOD',INTCB:'INTC',METAB:'META',MSFTB:'MSFT',MSTRB:'MSTR',MUB:'MU',NVDAB:'NVDA',PLTRB:'PLTR',SKHYB:'SKHY',SNDKB:'SNDK',TSLAB:'TSLA',TSMB:'TSM'};
async function officialGet(path){for(const base of API_BASES){try{const r=await fetch(base+path,{cache:'no-store',mode:'cors'}),text=await r.text();if(r.ok)return JSON.parse(text)}catch{}}throw new Error('合约行情接口暂不可用（已尝试多个官方节点）')}
async function spotOfficialGet(path){for(const base of SPOT_API_BASES){try{const r=await fetch(base+path,{cache:'no-store',mode:'cors'}),text=await r.text();if(r.ok)return JSON.parse(text)}catch{}}throw new Error('现货行情接口暂不可用（已尝试多个官方节点）')}
function ema99(values){if(values.length<99)return[];const out=[values.slice(0,99).reduce((a,b)=>a+b,0)/99],alpha=.02;for(let i=99;i<values.length;i++)out.push(values[i]*alpha+out[out.length-1]*(1-alpha));return out}
function baseKey(symbol){const stripped=cleanSymbol(symbol).replace(/(USDT|USDC)$/,'');return UNDERLYING_ALIASES[stripped]||stripped}
function angle(now,old,n){return Math.atan(((now/old-1)*100)/n)*180/Math.PI}
function trend(a){return a>=.3?'强势上涨':a>=.1?'温和上涨':a>-.1?'基本走平':a>-.3?'温和下降':'强势下降'}
function momentum(a5,a10,a20){if(a5>a10&&a10>a20&&a20>0)return'加速上涨';if(a20>a10&&a10>a5&&a10>0)return'上涨减速';if(a5<a10&&a10<a20&&a20<0)return'加速下降';if(a20<a10&&a10<a5&&a10<0)return'下降减速';return'方向混乱'}
function curveConfirmation(values){const bars=24,offset=10,end=values.length-offset,start=end-bars-1;if(start<0)return{confirmed:false,direction:'flat',averageAngle:0,peakAngle:0,directionalRatio:0,netChangePct:0,roughness:Infinity,bars:0};const segment=values.slice(start,end),averageAngle=angle(segment.at(-1),segment[0],bars),direction=averageAngle>=.1?'up':averageAngle<=-.1?'down':'flat',slopes=segment.slice(1).map((value,i)=>angle(value,segment[i],1)),sign=direction==='up'?1:direction==='down'?-1:0,directionalRatio=sign?slopes.filter(s=>s*sign>0).length/slopes.length:0,peakAngle=Math.max(0,...slopes.map(s=>s*sign)),netChangePct=Math.abs((segment.at(-1)/segment[0]-1)*100),totalVariation=slopes.slice(1).reduce((sum,s,i)=>sum+Math.abs(s-slopes[i]),0),roughness=peakAngle>0?totalVariation/peakAngle:Infinity;return{confirmed:sign!==0&&directionalRatio>=.75&&peakAngle>=.12&&netChangePct>=.04&&roughness<=5,direction,averageAngle,peakAngle,directionalRatio,netChangePct,roughness,bars}}
function reversalRecommendation(values,current){const curve=curveConfirmation(values);if(curve.confirmed&&curve.direction==='down'&&current>0)return{side:'做多',curve};if(curve.confirmed&&curve.direction==='up'&&current<0)return{side:'做空',curve};return{side:'观望',curve}}
async function mapLimit(items,limit,task){const out=new Array(items.length);let cursor=0;async function worker(){while(cursor<items.length){const i=cursor++;try{out[i]={ok:true,value:await task(items[i])}}catch(error){out[i]={ok:false,error}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
async function loadPinnedChanges(result){await Promise.all(result.pinned.map(async item=>{if(!item.row)return;try{const ticker=await officialGet('/fapi/v1/ticker/24hr?symbol='+encodeURIComponent(item.symbol)),change=Number(ticker.priceChangePercent);item.row.priceChangePct=Number.isFinite(change)?change:0}catch{item.row.priceChangePct=0}}));return result}
async function loadDailyBackgrounds(result){const targets=[...new Map([...result.rows,...result.positionRows].map(row=>[row.symbol,row.symbol])).values()],backgrounds=new Map;const settled=await mapLimit(targets,3,async symbol=>{const raw=await officialGet('/fapi/v1/klines?symbol='+encodeURIComponent(symbol)+'&interval=1d&limit=150'),candles=raw.map(k=>({close:Number(k[4]),closeTime:Number(k[6])})).filter(k=>k.closeTime<Date.now()&&Number.isFinite(k.close)&&k.close>0),values=ema99(candles.map(k=>k.close));if(values.length<12)throw new Error('日线 EMA99 历史不足');const close=candles.at(-1).close,current=values.at(-1),angle10=angle(current,values.at(-11),10),above=close>current,label=angle10>=.1&&above?'初步牛市背景':angle10<=-.1&&!above?'初步熊市背景':angle10<0&&above||angle10>0&&!above?'日线转折/分化':'日线中性';return{symbol,value:{label,ema99:current,angle10,distancePct:(close/current-1)*100,lastClosedTime:candles.at(-1).closeTime}}});settled.forEach(item=>{if(item.ok)backgrounds.set(item.value.symbol,item.value.value)});[...result.rows,...result.positionRows].forEach(row=>row.dailyBackground=backgrounds.get(row.symbol)||null);return result}
async function loadHourlyExitSignals(result){if(!EXIT_STRATEGY_ENABLED||!result.positionRows.length)return result;await Promise.all(result.positionRows.map(async row=>{try{const raw=await officialGet('/fapi/v1/klines?symbol='+encodeURIComponent(row.symbol)+'&interval=1h&limit=220'),candles=raw.map(k=>({high:Number(k[2]),low:Number(k[3]),close:Number(k[4]),closeTime:Number(k[6])})).filter(k=>k.closeTime<Date.now()&&Number.isFinite(k.close)&&k.close>0),values=ema99(candles.map(k=>k.close));if(values.length<12)throw new Error('1H EMA99 历史不足');const current=values.at(-1);row.hourly={ema99:current,angle5:angle(current,values.at(-6),5),angle10:angle(current,values.at(-11),10),twoClosesBelowEma:candles.at(-1).close<values.at(-1)&&candles.at(-2).close<values.at(-2),twoClosesAboveEma:candles.at(-1).close>values.at(-1)&&candles.at(-2).close>values.at(-2),lastClosedTime:candles.at(-1).closeTime}}catch{row.hourly=null}}));return result}
async function scanDirect(){
  const started=Date.now(),stable=new Set(['USDT','USDC','FDUSD','TUSD','BUSD','DAI','USDP','USDE','PYUSD']),tradfiBaseSet=new Set(TRADFI_PAIRS.map(baseKey));
  $('#status').textContent='正在获取币圈合约、现货与 TradFi 成交额…';
  const [info,tickers,premiums,spotResult]=await Promise.all([officialGet('/fapi/v1/exchangeInfo'),officialGet('/fapi/v1/ticker/24hr'),officialGet('/fapi/v1/premiumIndex'),spotOfficialGet('/api/v3/ticker/24hr').then(value=>({value})).catch(error=>({error}))]);
  const volumes=new Map(tickers.map(x=>[x.symbol,Number(x.quoteVolume)])),marks=new Map(premiums.map(x=>[x.symbol,Number(x.markPrice)])),spotVolumes=new Map;
  for(const ticker of spotResult.value||[]){const symbol=cleanSymbol(ticker.symbol),quote=symbol.endsWith('USDT')?'USDT':symbol.endsWith('USDC')?'USDC':null,volume=Number(ticker.quoteVolume);if(!quote||!Number.isFinite(volume)||volume<0)continue;const base=baseKey(symbol.slice(0,-quote.length));spotVolumes.set(base,(spotVolumes.get(base)||0)+volume)}
  const allSupported=info.symbols.filter(x=>['USDT','USDC'].includes(x.quoteAsset)&&x.contractType==='PERPETUAL'&&x.status==='TRADING'&&!stable.has(x.baseAsset)&&!/(UP|DOWN|BULL|BEAR)$/.test(x.baseAsset)&&(!x.deliveryDate||x.deliveryDate>Date.now()+86400000)).flatMap(x=>{const futuresQuoteVolume=volumes.get(x.symbol),spotQuoteVolume=spotVolumes.get(baseKey(x.baseAsset))||0;return futuresQuoteVolume!==undefined&&marks.has(x.symbol)?[{symbol:x.symbol,quoteVolume:futuresQuoteVolume+spotQuoteVolume,futuresQuoteVolume,spotQuoteVolume,markPrice:marks.get(x.symbol)}]:[]}).sort((a,b)=>b.quoteVolume-a.quoteVolume);
  const allBulk=allSupported.filter(x=>x.symbol.endsWith('USDT')),cryptoEligible=allBulk.filter(x=>!tradfiBaseSet.has(baseKey(x.symbol)));
  const tradfiMetaSettled=await mapLimit(TRADFI_PAIRS,4,async symbol=>{const [ticker,premium]=await Promise.all([officialGet('/fapi/v1/ticker/24hr?symbol='+encodeURIComponent(symbol)),officialGet('/fapi/v1/premiumIndex?symbol='+encodeURIComponent(symbol))]);const futuresQuoteVolume=Number(ticker.quoteVolume),spotQuoteVolume=spotVolumes.get(baseKey(symbol))||0,markPrice=Number(premium.markPrice);if(!Number.isFinite(futuresQuoteVolume)||!Number.isFinite(markPrice))throw new Error('TradFi 合约行情字段无效');return{symbol,quoteVolume:futuresQuoteVolume+spotQuoteVolume,futuresQuoteVolume,spotQuoteVolume,markPrice}});
  const tradfiEligible=tradfiMetaSettled.flatMap(x=>x.ok?[x.value]:[]).sort((a,b)=>b.quoteVolume-a.quoteVolume),tradfiMap=new Map(tradfiEligible.map(x=>[x.symbol,x]));
  const resolvePosition=key=>{const q=cleanSymbol(key),wanted=q.endsWith('USDT')||q.endsWith('USDC')?[q]:[q+'USDT',q+'USDC'];return wanted.map(symbol=>tradfiMap.get(symbol)||allSupported.find(x=>x.symbol===symbol)).find(Boolean)};
  const positionMatches=Object.keys(positions).flatMap(key=>{const candidate=resolvePosition(key);return candidate?[{key,candidate}]:[]});
  const heldBases=new Set(positionMatches.map(x=>baseKey(x.candidate.symbol))),reserveCount=Math.min(10,heldBases.size+3);
  const candidateMap=new Map([...PINNED_PAIRS.map(x=>tradfiMap.get(x.symbol)||cryptoEligible.find(c=>c.symbol===x.symbol)).filter(Boolean),...positionMatches.map(x=>x.candidate),...cryptoEligible.slice(0,10+reserveCount),...tradfiEligible.slice(0,10+reserveCount)].map(x=>[x.symbol,x])),candidates=[...candidateMap.values()];
  $('#status').textContent='正在扫描币圈、股票与已持仓候选共 '+candidates.length+' 个…';
  const settled=await mapLimit(candidates,3,async c=>{
    const [raw,oi]=await Promise.all([officialGet('/fapi/v1/klines?symbol='+encodeURIComponent(c.symbol)+'&interval=4h&limit=320'),officialGet('/fapi/v1/openInterest?symbol='+encodeURIComponent(c.symbol))]);
    const candles=raw.map(k=>({high:Number(k[2]),low:Number(k[3]),close:Number(k[4]),closeTime:Number(k[6])})).filter(k=>k.closeTime<Date.now()&&Number.isFinite(k.close)&&k.close>0);
    if(candles.length<150)throw new Error('已收盘4H K线不足150根（实际 '+candles.length+'）');
    const values=ema99(candles.map(k=>k.close));
    if(values.length<35)throw new Error('EMA99历史不足');
    const current=values.at(-1),a5=angle(current,values.at(-6),5),a10=angle(current,values.at(-11),10),a20=angle(current,values.at(-21),20),recommendation=reversalRecommendation(values,a10),recommendedSide=recommendation.side,curve=recommendation.curve;
    const structureCandles=candles.slice(-60),rawStructuralStop=recommendedSide==='做多'?Math.min(...structureCandles.map(k=>k.low)):recommendedSide==='做空'?Math.max(...structureCandles.map(k=>k.high)):null,suggestedStop=rawStructuralStop===null?null:recommendedSide==='做多'?rawStructuralStop*.997:rawStructuralStop*1.003,stopDistancePct=suggestedStop===null?null:Math.abs(suggestedStop/c.markPrice-1)*100,openInterest=Number(oi.openInterest);
    const twoClosesBelowEma=candles.at(-1).close<values.at(-1)&&candles.at(-2).close<values.at(-2),twoClosesAboveEma=candles.at(-1).close>values.at(-1)&&candles.at(-2).close>values.at(-2),twoBarsNoNewHigh=candles.at(-1).high<=candles.at(-2).high&&candles.at(-2).high<=candles.at(-3).high,twoBarsNoNewLow=candles.at(-1).low>=candles.at(-2).low&&candles.at(-2).low>=candles.at(-3).low;
    const atr14=exitAtr(candles,14),atr7=exitAtr(candles,7),atr28=exitAtr(candles,28),volatilityRatio=atr28>0?atr7/atr28:1;
    return{symbol:c.symbol,quoteVolume:c.quoteVolume,openInterest,openInterestNotional:openInterest*c.markPrice,markPrice:c.markPrice,ema99:current,distancePct:(c.markPrice/current-1)*100,angle5:a5,angle10:a10,angle20:a20,atr14,volatilityRatio,curve,recommendedSide,suggestedStop,stopDistancePct,emaChange10Pct:(current/values.at(-11)-1)*100,trend:trend(a10),momentum:momentum(a5,a10,a20),possibleTurn:a5>0&&a10<=0?'可能由负转正':a5<0&&a10>=0?'可能由正转负':null,twoClosesBelowEma,twoClosesAboveEma,twoBarsNoNewHigh,twoBarsNoNewLow,lastClosedTime:candles.at(-1).closeTime}
  });
  const errors=tradfiMetaSettled.flatMap((x,i)=>x.ok?[]:[{symbol:TRADFI_PAIRS[i],error:x.error.message}]),good=[];
  settled.forEach((x,i)=>x.ok?good.push(x.value):errors.push({symbol:candidates[i].symbol,error:x.error.message}));
  const goodMap=new Map(good.map(x=>[x.symbol,x])),cryptoAvailable=cryptoEligible.flatMap(x=>goodMap.has(x.symbol)&&!heldBases.has(baseKey(x.symbol))?[goodMap.get(x.symbol)]:[]),stockAvailable=tradfiEligible.flatMap(x=>goodMap.has(x.symbol)&&!heldBases.has(baseKey(x.symbol))?[goodMap.get(x.symbol)]:[]),cryptoRows=cryptoAvailable.slice(0,10),stockRows=stockAvailable.slice(0,10),selectedSymbols=new Set([...cryptoRows,...stockRows].map(x=>x.symbol)),fallbackRows=[...cryptoAvailable,...stockAvailable].filter(x=>!selectedSymbols.has(x.symbol)).sort((a,b)=>b.quoteVolume-a.quoteVolume).slice(0,20-cryptoRows.length-stockRows.length),rows=[...cryptoRows,...stockRows,...fallbackRows].slice(0,20).map((x,i)=>({rank:i+1,marketType:tradfiBaseSet.has(baseKey(x.symbol))?'股票':'币圈',...x})),positionRows=positionMatches.flatMap(x=>goodMap.has(x.candidate.symbol)?[{...goodMap.get(x.candidate.symbol),positionKey:x.key}]:[]),pinned=PINNED_PAIRS.map(x=>({...x,row:goodMap.get(x.symbol)||null}));
  if(!rows.length)throw new Error('没有交易对成功完成扫描。\\n'+errors.map(e=>e.symbol+': '+e.error).join('\\n'));
  const up=rows.filter(r=>r.angle10>=.1).length,down=rows.filter(r=>r.angle10<=-.1).length,flat=rows.length-up-down,above=rows.filter(r=>r.markPrice>r.ema99).length,below=rows.filter(r=>r.markPrice<r.ema99).length,ratio=n=>n/rows.length*100,accUp=rows.filter(r=>r.momentum==='加速上涨').length,accDown=rows.filter(r=>r.momentum==='加速下降').length;
  const regime=up/rows.length>=.7&&above/rows.length>=.7?'趋势扩散上涨':down/rows.length>=.7&&below/rows.length>=.7?'趋势扩散下跌':up>down&&above>below?'局部上涨':down>up&&below>above?'局部下跌':'震荡分化';
  return{source:'Official market API (browser direct)',liquiditySource:spotResult.value?'合约+现货':'仅合约（现货暂不可用）',scannedAt:Date.now(),durationMs:Date.now()-started,rows,positionRows,pinned,composition:{crypto:rows.filter(r=>r.marketType==='币圈').length,stocks:rows.filter(r=>r.marketType==='股票').length},errors,highlights:{steepestUp:[...rows].filter(r=>r.angle10>0).sort((a,b)=>b.angle10-a.angle10).slice(0,5),steepestDown:[...rows].filter(r=>r.angle10<0).sort((a,b)=>a.angle10-b.angle10).slice(0,5),acceleratingUp:rows.filter(r=>r.momentum==='加速上涨'),acceleratingDown:rows.filter(r=>r.momentum==='加速下降'),turningPositive:rows.filter(r=>r.possibleTurn==='可能由负转正'),turningNegative:rows.filter(r=>r.possibleTurn==='可能由正转负'),farFromEma:rows.filter(r=>Math.abs(r.distancePct)>5)},market:{total:rows.length,up:{count:up,pct:ratio(up)},down:{count:down,pct:ratio(down)},flat:{count:flat,pct:ratio(flat)},above:{count:above,pct:ratio(above)},below:{count:below,pct:ratio(below)},acceleratingUp:accUp,acceleratingDown:accDown,regime},lastClosedTime:Math.max(...rows.map(r=>r.lastClosedTime))}
}
async function runScan(){const b=$('#scan');if(b.disabled)return;b.disabled=true;b.textContent='扫描中…';$('#status').className='muted';try{render(await loadHourlyExitSignals(await loadDailyBackgrounds(await loadPinnedChanges(await scanDirect()))))}catch(e){$('#status').className='error';$('#status').textContent='扫描失败：'+e.message+'\\n\\n若仍失败，请确认当前网络可以访问行情接口。'}finally{b.disabled=false;b.textContent='立即扫描'}}
$('#scan').onclick=runScan;
$('#manual-position').onclick=openManualPosition;
$('#share-positions').onclick=sharePositions;
$('#pos-cancel').onclick=()=>$('#position-dialog').close();
$('#position-form').onsubmit=e=>{e.preventDefault();const symbol=cleanSymbol($('#pos-symbol').value),entry=Number($('#pos-entry').value)||0,stop=Number($('#pos-stop').value)||0,side=$('#pos-side').value;if(!symbol)return;const old=positions[symbol],now=Date.now(),keep=old&&old.side===side?old.tracking:null;positions[symbol]={side,entry,stop,tracking:keep?{...keep,updatedAt:now}:{trackedAt:now,updatedAt:now,lastScanAt:0,bestPrice:0,protectiveStop:stop}};savePositions();$('#position-dialog').close();data=undefined;renderPositions();runScan()};
const sharedImport=importSharedPositions();if(sharedImport!==null){const notice=$('#sync-notice');notice.hidden=false;notice.className=typeof sharedImport==='number'?'up':'error';notice.textContent=typeof sharedImport==='number'?'已从分享链接自动导入 '+sharedImport+' 个仓位。':'分享链接导入失败：'+sharedImport.error}
renderPositions();
runScan();
</script></body></html>`;
}

export const PAGE = buildPage(true);
