export const PAGE = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>4H EMA99 趋势扫描器</title>
<style>
:root{color-scheme:dark;--bg:#07100e;--card:#0d1916;--line:#20332d;--text:#e9f5f0;--muted:#8aa399;--green:#35d59a;--red:#ff6b6b}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% 0,#143027 0,#07100e 42%);color:var(--text);font:14px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}
main{max-width:1440px;margin:auto;padding:32px 20px 60px}header{display:flex;gap:20px;align-items:end;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:24px}
h1{font:700 clamp(25px,4vw,44px)/1.1 system-ui;margin:0}h2{font:700 19px system-ui;margin:0 0 16px}.eyebrow,.muted{color:var(--muted)}
button{border:0;border-radius:8px;background:var(--green);color:#03120d;font:700 15px system-ui;padding:13px 22px;cursor:pointer;min-height:46px}button:disabled{opacity:.55;cursor:wait}
#status{margin:18px 0;min-height:24px}.error{color:#ff9b9b;white-space:pre-wrap}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}
.card{background:color-mix(in srgb,var(--card) 90%,transparent);border:1px solid var(--line);border-radius:12px;padding:17px}.value{font:700 25px system-ui}.up{color:var(--green)}.down{color:var(--red)}
.section{margin-top:30px}.groups{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.group ul{margin:0;padding:0;list-style:none}.group li{display:grid;grid-template-columns:80px 1fr auto;gap:10px;padding:8px 0;border-top:1px solid var(--line)}
.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:12px}table{width:100%;border-collapse:collapse;white-space:nowrap;background:var(--card)}th,td{padding:10px 11px;text-align:right;border-bottom:1px solid var(--line)}
th{position:sticky;top:0;background:#13231e;color:var(--muted);font-size:12px;cursor:pointer}th:nth-child(2),td:nth-child(2){text-align:left;position:sticky;left:0;background:inherit}footer{margin-top:32px;color:var(--muted);text-align:center}
@media(max-width:760px){main{padding:20px 12px 40px}header{align-items:stretch;flex-direction:column}.grid,.groups{grid-template-columns:1fr}.group li{grid-template-columns:72px 1fr auto}button{width:100%}}
</style></head><body><main>
<header><div><div class="eyebrow">BINANCE USDⓈ-M FUTURES · 4H</div><h1>EMA99 趋势扫描器</h1><p class="muted">按 24h 成交额筛选高流动性永续合约，只分析已收盘 K 线。</p></div><button id="scan">立即扫描</button></header>
<div id="status" class="muted">点击按钮实时请求币安官方 API。</div>
<section id="market" class="grid" hidden></section>
<section id="highlights" class="section" hidden><h2>重点筛选结果</h2><div class="groups" id="groups"></div></section>
<section id="full" class="section" hidden><h2>完整扫描表 <span class="muted">（点击表头排序）</span></h2><div class="table-wrap"><table><thead id="head"></thead><tbody id="body"></tbody></table></div></section>
<section id="issues" class="section" hidden><h2>跳过的交易对</h2><div class="card error" id="issue-list"></div></section>
<footer>技术指标不构成投资建议。</footer></main>
<script>
const $=s=>document.querySelector(s),fmt=(n,d=2)=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:d}),pct=n=>(n>=0?'+':'')+n.toFixed(2)+'%',ang=n=>(n>=0?'+':'')+n.toFixed(3)+'°',time=t=>new Date(t).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
const cols=[['rank','成交额排名'],['symbol','交易对'],['quoteVolume','24h Quote Volume'],['openInterest','Open Interest 数量'],['openInterestNotional','OI 名义价值'],['markPrice','Mark Price'],['ema99','EMA99'],['distancePct','距 EMA99'],['angle5','5根角度'],['angle10','10根角度'],['angle20','20根角度'],['emaChange10Pct','EMA 10根累计变化'],['trend','趋势分类'],['momentum','角度动量'],['lastClosedTime','已收盘4H结束时间']];
let data,sortKey='angle10',sortAsc=false;
function klass(n){return n>0?'up':n<0?'down':''}
function val(r,k){if(['distancePct','emaChange10Pct'].includes(k))return pct(r[k]);if(k.startsWith('angle'))return ang(r[k]);if(k==='lastClosedTime')return time(r[k]);if(['quoteVolume','openInterest','openInterestNotional'].includes(k))return fmt(r[k],0);if(['markPrice','ema99'].includes(k))return fmt(r[k],8);return r[k]}
function table(){const rows=[...data.rows].sort((a,b)=>{const x=a[sortKey],y=b[sortKey];return (typeof x==='number'?x-y:String(x).localeCompare(String(y)))*(sortAsc?1:-1)});$('#head').innerHTML='<tr>'+cols.map(c=>'<th data-k="'+c[0]+'">'+c[1]+(sortKey===c[0]?(sortAsc?' ↑':' ↓'):'')+'</th>').join('')+'</tr>';$('#body').innerHTML=rows.map(r=>'<tr>'+cols.map(c=>'<td class="'+(c[0].startsWith('angle')||c[0].endsWith('Pct')?klass(r[c[0]]):'')+'">'+val(r,c[0])+'</td>').join('')+'</tr>').join('');document.querySelectorAll('th').forEach(x=>x.onclick=()=>{const k=x.dataset.k;sortAsc=sortKey===k?!sortAsc:false;sortKey=k;table()})}
function group(title,rows){return '<div class="card group"><h2>'+title+' <span class="muted">'+rows.length+'</span></h2><ul>'+(rows.length?rows.map(r=>'<li><b>'+r.symbol+'</b><span class="'+klass(r.angle10)+'">'+ang(r.angle10)+' · '+r.trend+' · '+r.momentum+'</span><span>'+pct(r.distancePct)+'</span></li>').join(''):'<li class="muted">暂无</li>')+'</ul></div>'}
function render(d){data=d;const m=d.market;$('#status').textContent='扫描时间（UTC+8）：'+time(d.scannedAt)+' · 最近已收盘4H：'+time(d.lastClosedTime)+' · 耗时 '+fmt(d.durationMs,0)+' ms · 成功 '+d.rows.length+' 个';$('#market').innerHTML=[['市场状态',m.regime,''],['EMA99 向上',m.up.count+' / '+m.up.pct.toFixed(0)+'%','up'],['EMA99 向下',m.down.count+' / '+m.down.pct.toFixed(0)+'%','down'],['基本走平',m.flat.count+' / '+m.flat.pct.toFixed(0)+'%',''],['Price > EMA99',m.above.count+' / '+m.above.pct.toFixed(0)+'%','up'],['Price < EMA99',m.below.count+' / '+m.below.pct.toFixed(0)+'%','down'],['加速上涨',m.acceleratingUp,'up'],['加速下降',m.acceleratingDown,'down']].map(x=>'<div class="card"><div class="muted">'+x[0]+'</div><div class="value '+x[2]+'">'+x[1]+'</div></div>').join('');const h=d.highlights;$('#groups').innerHTML=group('角度最陡上涨 Top 5',h.steepestUp)+group('角度最陡下跌 Top 5',h.steepestDown)+group('加速上涨',h.acceleratingUp)+group('加速下降',h.acceleratingDown)+group('可能由负转正',h.turningPositive)+group('可能由正转负',h.turningNegative)+group('距离 EMA99 超过 ±5%',h.farFromEma);['market','highlights','full'].forEach(x=>$('#'+x).hidden=false);table();if(d.errors.length){$('#issues').hidden=false;$('#issue-list').textContent=d.errors.map(e=>e.symbol+': '+e.error).join('\\n')}else $('#issues').hidden=true}
$('#scan').onclick=async()=>{const b=$('#scan');b.disabled=true;b.textContent='扫描中…';$('#status').className='muted';$('#status').textContent='正在获取合约、成交额、Mark Price、K线与 Open Interest…';try{const r=await fetch('/api/scan',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error+(j.details?'\\n'+JSON.stringify(j.details,null,2):''));render(j)}catch(e){$('#status').className='error';$('#status').textContent='扫描失败：'+e.message}finally{b.disabled=false;b.textContent='立即扫描'}};
</script></body></html>`;
